// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKGco8lhlh-rWUhcc4sJ70KvYrTYf8BDg',
    appId: '1:495225547524:web:4b61e62727f6ee0cb17e51',
    messagingSenderId: '495225547524',
    projectId: 'remed-aura-organic-store-fa690',
    authDomain: 'remed-aura-organic-store-fa690.firebaseapp.com',
    storageBucket: 'remed-aura-organic-store-fa690.firebasestorage.app',
    measurementId: 'G-NRCZN46FZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO_HHcTm6E3WtkSx4uY0d6VrJELs_EcYI',
    appId: '1:495225547524:android:57b7576fea29b1aab17e51',
    messagingSenderId: '495225547524',
    projectId: 'remed-aura-organic-store-fa690',
    storageBucket: 'remed-aura-organic-store-fa690.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGIcG2cg6OO8pvQ1VV7zi_s58_6lbgBdI',
    appId: '1:495225547524:ios:198eca317757db4fb17e51',
    messagingSenderId: '495225547524',
    projectId: 'remed-aura-organic-store-fa690',
    storageBucket: 'remed-aura-organic-store-fa690.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGIcG2cg6OO8pvQ1VV7zi_s58_6lbgBdI',
    appId: '1:495225547524:ios:198eca317757db4fb17e51',
    messagingSenderId: '495225547524',
    projectId: 'remed-aura-organic-store-fa690',
    storageBucket: 'remed-aura-organic-store-fa690.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKGco8lhlh-rWUhcc4sJ70KvYrTYf8BDg',
    appId: '1:495225547524:web:d7e124219c7666c1b17e51',
    messagingSenderId: '495225547524',
    projectId: 'remed-aura-organic-store-fa690',
    authDomain: 'remed-aura-organic-store-fa690.firebaseapp.com',
    storageBucket: 'remed-aura-organic-store-fa690.firebasestorage.app',
    measurementId: 'G-BHEYR2HVDY',
  );
}
